name: my first workflow | shell script 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: list files 
              run: ls -ltra

            - name: run shell script
              run:
                |
                chmod +x script.sh
                ./script.sh